name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          architecture: x64

      - name: Build project
        run: gradle clean build

      - name: Make gradlew executable
        run: chmod +x gradlew



  checkstyle:

    runs-on: ubuntu-latest
    needs: build
    name: checkstyle

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run checkstyle
        uses: nikitasavinov/checkstyle-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-pr-check'
          checkstyle_config: '${{ github.workspace }}/config/checkstyle/checkstyle.xml'


  coverage:
    runs-on: ubuntu-latest
    #permissions: write-all
    needs: build

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Coverage
        run: |
          chmod +x gradlew
          ./gradlew jacocoTestReport

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Coverage Results
          update-comment: true
