name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: |
          gradle clean build
          
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: testReport
          path: build/jacoco/test.exec 
          
      

  jacoco-report:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: testReport
          path: build/jacoco
                 
      - name: Make gradlew executable
        run: chmod +x gradlew          
      - name: Run Jacoco tests
        run: |
          ./gradlew jacocoTestReport


      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: |
            ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 80
          title: Code Coverage
          update-comment: true

  checkstyle_job:
    runs-on: ubuntu-latest
    name: Checkstyle
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Checkstyle
        uses: nikitasavinov/checkstyle-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-pr-check'
          tool_name: 'reviewdog'
          checkstyle_config: '${{ github.workspace }}/config/checkstyle/checkstyle.xml'
          fail_on_error: true
          level: 'error'
          filter_mode: nofilter
          
